### ISSUE TITLE
Sky texture vanished 

### ISSUE THREAD

**Issue by PablitoMarselo** [quek04/The-Undergarden#104]
The undergarden sky texture strangely dissapeared, I didnt interact with or moved the game files, it just randomly vanished.[
![Captura de pantalla (150)](https://user-images.githubusercontent.com/85983637/122167746-3ce00b00-ce30-11eb-9061-c8bda2e8767a.png)

**Comment by quek04** [comment]
That's how it's supposed to look. The Undergarden sky is just fog.
Also, you have night vision. It makes the sky bright.
