### ISSUE TITLE
I can't craft the catalyst.

### ISSUE THREAD

**Issue by IcyD1amond** [quek04/The-Undergarden#106]
I am playing the "Better Minecraft: OfflineTV Edition" mod and The Undergarden is one of the mods in it. I can't seem to craft the catalyst though. So I took all the mods out except "The Undergarden" and I still couldn't craft it. I've tried everything from starting a new world to completely reinstalling the game itself. Nothing seems to have worked.

**Comment by quek04** [comment]
Talk to the people who made the modpack, not me
