### ISSUE TITLE
Graphical aliasing artifacts when using optifine

### ISSUE THREAD

**Issue by Raccoon1400** [quek04/The-Undergarden#111]
In other words, I get staticy/grainy graphical noise. This occurs in the overworld, not just the undergarden. I tried older versions and this issue first appears in 0.5.3. Before that it is fine. I removed all other mods to make sure none of them were affecting it, it is the reaction between undergarden and optifine. My friend was able to repeat the issue on his machine.

**Comment by quek04** [comment]
Don't use Optifine.
