### ISSUE TITLE
help this mod got me banned from hypixel

### ISSUE THREAD

**Issue by andrew071117** [quek04/The-Undergarden#113]
remove this mod now it got me banned from hypixel

**Comment by OakBricks-old** [comment]
lol, what do you expect from joining hypixel with mods? a kiss on the cheeks? you can only use approved mods on hypixel afaik

**Comment by reetamb** [comment]
> remove this mod now it got me banned from hypixel

I'll find you.

**Comment by S10MC2015** [comment]
Lmao

**Comment by SammySemicolon** [comment]
I think u should pin this issue.
