### ISSUE TITLE
Undergarden freezes periodically. 

### ISSUE THREAD

**Issue by lithospace** [quek04/The-Undergarden#116]
So basically, I've entered the Undergarden, terrain seems to generate correctly, but it freezes for seconds at a time before unfreezing and even after leaving the dimension, it affects the overworld. Is there a compatibility patch needed/what mods is it not compatible with? I'm using this in the Better Minecraft Modpack v38. I figured out that the mod loads a shit ton of garbage memory, causing my PC to RAM freeze. And it's a lot of junk memory too. I dedicated 10 GB to this minecraft instance and it manages to bottleneck it. This didn't happen in version 5.0.2

**Comment by quek04** [comment]
I can't really help with this unless more information is provided.. so
