### ISSUE TITLE
Suggestion: JEED (Just Enough Effect Description) Compatibility

### ISSUE THREAD

**Issue by StrangerSon71** [quek04/The-Undergarden#117]
My previous opening comment was found to be incorrect, I apologize.

**Comment by StrangerSon71** [comment]
The fact that this is a 1.17 exclusive feature disappoints me. It shouldn't, you have the right to support newer versions exclusively, but it does.

**Comment by quek04** [comment]
You could easily backport it with just a resource pack 🤷

**Comment by StrangerSon71** [comment]
Or send it to the dev to implement on his side. Yeah, it's not that hard to work around.
