### ISSUE TITLE
Nargoyle drops

### ISSUE THREAD

**Issue by SilentNoob57** [quek04/The-Undergarden#126]
Hello, this is my first ever Github issue so dont expect much. Is it normal that Nargoyles do not drop strings? I've been killing a lot of them and even tried with looting enchantements to no avail. 

Edit: In the new version 1.18.2

**Comment by quek04** [comment]
This was removed a while ago, in favor of Mogmoss and Depthrock Beds

**Comment by SilentNoob57** [comment]
Thanks you, guess I've just been out of touch with changelogs for a while.
