### ISSUE TITLE
Bad compatibility with mod "Oh the Biomes You'll Go"

### ISSUE THREAD

**Issue by Jissee** [quek04/The-Undergarden#129]
MC Version: 1.18.2
Forge Version: 40.0.12

It has been confirmed that if I load "Oh the Biomes You'll Go" mod(BYG, Available at: https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go) and its dependency Terrablender(Available at: https://www.curseforge.com/minecraft/mc-mods/terrablender) together with the mod "The Undergarden", BYG mod can work well but the mod world of Undergarden can be damaged and its biomes will not appear in the world.

I am using the latest version of those three mods and they are the only mods in my client.

This issue has also been reported to BYG Team(https://github.com/AOCAWOL/BYG/).
![2022-03-29_14 52 10](https://user-images.githubusercontent.com/50765103/160551193-9fd1196d-5329-4a3f-bef1-5f736305924f.png)

**Comment by quek04** [comment]
I think TerraBlender fixed this a few hours ago.
