### ISSUE TITLE
Undergarden Portal not teleporting you when standing in it

### ISSUE THREAD

**Issue by KakashoLin** [quek04/The-Undergarden#133]
I am able to create the portal but standing in it does not teleport you. Looking on discord, other users are reporting similar issues. 

Using the mod, from the mod pack Better Minecraft Plus Edition by SharkieTV on Cruseforge.

**Comment by quek04** [comment]
You might be experiencing #122. Refer to this: https://github.com/quek04/The-Undergarden/issues/122#issuecomment-1069607462

**Comment by quek04** [comment]
Assuming you're not going to respond so I'm just going to close this.
