### ISSUE TITLE
New Brick Portal Created near the original when returning 

### ISSUE THREAD

**Issue by sthephanno1** [quek04/The-Undergarden#134]
When exiting the undergarden, another portal get created in the Overworld if you keep repeating this process more brick portals keep appearing in a stair-like patron separated by a few block
EDIT: Did it again to take screenshots now Portals just appear nearby, not like described before, only could take a ss of this in the undergarden, even installed a mod to fix the netherportals if it somehow fixed this but it didnt
![2022-04-15_00 08 30](https://user-images.githubusercontent.com/70006664/163523502-3fde8985-d24a-4369-8932-295ea53a92f8.png)
s

**Comment by quek04** [comment]
Version of Forge and Undergarden? Do you have any performance mods?

**Comment by KosChris** [comment]
Hi! This is also happening to me, exactly as OP described. When porting back and forth between the Undergarden and the Overworld, an new portal is created each time on either side. 
Undergarden version - 0.6.4
Forge version  - 40.0.32 (which I just realized is out of date)

I have a huge mod list, you asked the OP if they're using performance mods, I'm not sure which to look for specifically. 
Thanks! 

Edit: 
Updated Forge on client and server, same issue.

**Comment by MoshiiBromii** [comment]
I also get the same issue with my minecraft multiplayer world, it destroyed a chunk of my house. I built the portal in the basement below my house, now there's this 1 chunk that wont load no matter what you do. Unless if you have saved backups that was saved BEFORE having the portal, you can fix the issue by simply reverting to that backup that doesn't have the portal. 

Tried it again but this time outside of my base, the chunk issue is fixed, but it just keeps creating more portal.

**Comment by quek04** [comment]
This issue doesn't occur when the Undergarden is installed without any other mods. In the past it was caused by a performance mod called Performant, so if you have any performance mods I would recommend testing without them installed.

**Comment by MoshiiBromii** [comment]
Yeah I found out the issue why, secretrooms makes the chunks goes bye bye.
