### ISSUE TITLE
[1.18.2]  Stone portals automatically break themselves

### ISSUE THREAD

**Issue by Reshy** [quek04/The-Undergarden#136]
Having an issue with the mod, the stone based portal frames seem to self-destruct instantly, but the portals for the modded stones work as normal.
![2022-04-29_02 22 49](https://user-images.githubusercontent.com/2096384/165919115-d064aac4-553a-4f58-84ff-6a924664e09a.png)
![2022-04-29_02 26 32](https://user-images.githubusercontent.com/2096384/165919125-1b503529-2834-44bc-b3e7-0542cdfa4042.png)

**Comment by Fooshcookie** [comment]
Unsupported version. Two years old. Closing.
