### ISSUE TITLE
There are no minerals or trees in the underground world？！

### ISSUE THREAD

**Issue by QianMuu** [quek04/The-Undergarden#139]
I succeeded in creating the underground world.

But I found that it did not produce ore,

There were no trees, which made it impossible for me to continue to live.

I wonder what's wrong?

**Comment by enderfree** [comment]
Which version? I am using the latest in 1.18.2 right now and I have coal and Chroganium

**Comment by quek04** [comment]
??? Chroganium isn't a thing in the mod, and there's more things than just coal. Usually world gen features not existing is caused by another mod

**Comment by enderfree** [comment]
*Crogglum, sorry
