### ISSUE TITLE
Wrong and missing tags

### ISSUE THREAD

**Issue by RCXcrafter** [quek04/The-Undergarden#140]
Undergarden 0.7.0
* The forge:nuggets/cloggrum tag is applied to the cloggrum ingot instead of the nugget
* The froststeel and forgotten metal ingots/nuggets also have this problem
* The block of forgotten metal is missing the forge:storage_blocks/forgotten_metal tag
* The raw cloggrum item is missing the forge:raw_materials/cloggrum tag and the block of raw cloggrum is missing the forge:storage_blocks/raw_cloggrum tag
* Froststeel is also missing its raw ore tags
* I think the utherium shard should maybe have the forge:nuggets/utherium tag but I'm not entirely sure about that

**Comment by Xaidee** [comment]
Luckily there's not really any other mods that would need most of those tags since the materials are so unique to the undergarden mod lol

**Comment by RCXcrafter** [comment]
Jaopca does rely on these tags being correct to function properly and the undergarden integration I made for my tinkers construct addon also doesn't quite work properly because of this

**Comment by quek04** [comment]
oh my god how did i not realize this
