### ISSUE TITLE
Crashing 3 minutes after entering portal - Valhelsia 3 modpack

### ISSUE THREAD

**Issue by ChielTheOread** [quek04/The-Undergarden#145]
**Minecraft version:** 1.16.5
**Forge version:** 36.2.31
**Mod version:** The_Undergarden-1.16.5-0.5.5
**Mod add on:** Undergarden-Tetra Patch-1.2.1
**Modpack:** Valhelsia 3.5.1

I added some mods including The Undergarden, and I'm not sure what's causing the issue, all i know is that after entering The Undergarden portal, it crashes after 3 minutes failing to load in. 

Here's my crash report:
[crash-2022-06-28_15.17.15-server.txt](https://github.com/quek04/The-Undergarden/files/9004233/crash-2022-06-28_15.17.15-server.txt)
 
Here's an image of the mods i added to Valhelsia 3 highlighted in blue:
![mods added to valhelsia](https://user-images.githubusercontent.com/87271783/176269598-3047b843-bafd-40f4-9a65-4b8f5875241e.png)

**Comment by quek04** [comment]
1.16.5 is unsupported
