### ISSUE TITLE
[1.18.2] world breaks when removing

### ISSUE THREAD

**Issue by Dontrell94** [quek04/The-Undergarden#147]
When removing mod, the save throws an error stating that it cannot load due to an issue trying to load noise settings from the mod's datapack.

java.lang.IllegalStateException: Trying to access unbound value 'ResourceKey[minecraft:worldgen/noise_settings / undergarden:undergarden]' from registry Registry[ResourceKey[minecraft:root / minecraft:worldgen/noise_settings] (Stable)]

https://gist.github.com/Dontrell94/9fe23cc83dcd5fb733e341e1b07f4e21

**Comment by eisnan** [comment]
Hi @quek04! Any news on this? I am getting the same error.

**Comment by AmberGoop** [comment]
There is no further updates for 1.18.2, unless the mod is the one breaking things. This case, it is not the mod, it is user error and cannot be fixed by us. You should not be removing dimension mods (or any non-client ONLY mods, for that matter) EVER from your saves. It will result in broken saves, end of story. There is no fix for this other than don't do that.

**Comment by Dontrell94** [comment]
I stepped away from this issue as there was seemingly no response, but now I feel that I have to clarify a little. When making a pack, it's normal for the mod list to change to either accommodate incompatibilities or because the mod ends up having no use because of other mods. Usually, my mod list include multiple dim mods and non dim mods. when a mod that is pre determined to be in the pack (but is awaiting an update) gets added and breaks everything with the only fix being to remove 1 dim mod.... and the removal of that mod requires everyone to reset saves due to a world gen modification made by a mod, that's not really user error, it's trying to make a pack work by extracting the only one causing issues and then that breaks months old worlds because the original author couldn't keep their world gen modifications separate in their mod.

Bear in mind that I come at this from a standpoint of every other dim mod not breaking saves that I have used or even mods that tweak the worldgen don't break saves, they just stop generating the world that way.

**Comment by bconlon1** [comment]
This was a Forge issue, not a mod issue: https://github.com/MinecraftForge/MinecraftForge/issues/8800. It has since been fixed by them in 1.19.

**Comment by AmberGoop** [comment]
that's probably why it ain't working in 1.18 here

**Comment by eisnan** [comment]
Actually I studied a bit the stacktrace and went into level.dat and removed the dimensions from there. That fixed things up, but thanks a lot for looking over this!!
