### ISSUE TITLE
[1.18.2] Portal generation: New portal every time

### ISSUE THREAD

**Issue by drakray** [quek04/The-Undergarden#148]
Every time I use a portal to go to and from Undergarden, a new portal is created

I am playing a superflat Void world when I saw this bug, I tried remaking the portal by checking the coordinate (overworld divided by 4 seems to be the rule), but even then it just pop a new portal right next the the one I made in the Overworld (OW portal at -26:20, made an UG at -6:5, return to a new portal at -25:22 OW portal was North-South, made the UG portal the same, new portal is East-West)

Minecraft 1.18.2
Forge 40.1.73
Undergarden 0.7.1
Lot of other mods, [full list here](https://pastebin.com/Py66JSCN)

**Comment by NightUndead** [comment]
I have the same issue in a custom pack of mine. This has a list of the mods me and Drakray has in common:
https://pastebin.com/0G0T2YiU

**Comment by Burning-Cactus** [comment]
I'm like 90% sure that this is an issue with Radium breaking POIs. Try removing that mod, or at the least adding the line `mixin.ai.poi=false` in Radium's config file.

**Comment by drakray** [comment]
Removing Radium does not work(tried the config first, didn't work either)
![2022-08-11_13 18 58](https://user-images.githubusercontent.com/4303126/184194497-87b2da47-dae7-4d70-ad17-ed65664a5721.png)

**Comment by freezox** [comment]
Same problem here :(

**Comment by PlutoTramble** [comment]
I got the same problem in version 1.19.2 .

As @Burning-Cactus mentionned, I added the line `mixin.ai.poi=false` in Radium's config file since I happen to also have that mod, then I installed the NetherPortalFix mod.

Now there isn't a portal generated every time I travel to the dimension.

I haven't tested for 1.18.2, but it might work on that version.

**Comment by luxidoptera** [comment]
Having a similar problem on 1.20.1. It drops me in the middle of nowhere when leaving the Undergarden, generating a new portal ~40-50 blocks south and ~30-40 blocks east of the original location.

NetherPortalFix fixes the issue.

**Comment by Fooshcookie** [comment]
Unsupported version. Two years old. Closing.
