### ISSUE TITLE
Portal still doesnt work on servers 

### ISSUE THREAD

**Issue by FullMetalMaster** [quek04/The-Undergarden#15]
using forge 1.16.1 32.0.88 still cant go in the dim just doesnt load.

**Comment by quek04** [comment]
i'm going to need more information

**Comment by FullMetalMaster** [comment]
what do you need? i walk right though it works in single player just not on the 32.0.88 forge server side, if you try to go in you walk right though you dont load at all not errors etc if theres anything you want me to test let me know

**Comment by quek04** [comment]
are you in creative or survival? in survival mode you have to stand in it for a bit, like a nether portal. it just doesn't show a screen effect

**Comment by FullMetalMaster** [comment]
both seems not to work i stand in it for a while in survival mode and no dice and creative i should start to pop in i just go right through the green portal swirls

**Comment by smokyhishn** [comment]
I got same issue on Forge 32.0.98,
Tried survival and creative and tried different sized portals

**Comment by FullMetalMaster** [comment]
Forge 32.0.98 also is not sable at all some mods still have issues not wanting to load in it

**Comment by AlscarB** [comment]
Marked as completed? There's no solution or suggestion or result

**Comment by quek04** [comment]
this was 4 years ago and nobody gave any helpful information

**Comment by AlscarB** [comment]
Can activate the portal fine, however when walking inside of it/standing inside of it. Nothing happens, every other dimensional portal works except the Undergarden. This is on the RAD2 pack specifically but the error occurs separate to the pack as well
![image](https://github.com/quek04/The-Undergarden/assets/54087010/111d5cde-4442-440c-a81b-51c5aa5a0585)
![image](https://github.com/quek04/The-Undergarden/assets/54087010/64029ef3-67f9-4f4c-86a9-d752fe1fa85b)

**Comment by AlscarB** [comment]
FYI for those finding this after coming across this issue today, this thread should be marked as 'Not Planned' rather than completed because they haven't and don't plan on attempting to fix this issue. Sorry to be the one to tell you
