### ISSUE TITLE
[1.18.2] Invalid Texture on Virulent Mixture

### ISSUE THREAD

**Issue by Reshy** [quek04/The-Undergarden#151]
![2022-08-28_06 53 17](https://user-images.githubusercontent.com/2096384/187077310-a68e3876-d807-45c1-ba3b-65a7b9a6d0d3.png)
When next to non-full opaque blocks the liquid's texture is removed incorrectly leaving a placeholder.

Also, despite having water physics, the Virulent Mixture cannot create an infinite source like water can:
![2022-08-28_06 56 09](https://user-images.githubusercontent.com/2096384/187077486-9e99c0cf-bce2-4da3-899a-4ddfe007f593.png)

**Comment by quek04** [comment]
![image](https://user-images.githubusercontent.com/55364841/187078511-a15aa3b1-91af-49ff-951e-17a2bfe7e0e6.png)
fixed the texture thing. 
virulent isnt supposed to be infinite, that's intentional
