### ISSUE TITLE
[1.18.2] Portal doesn´t teleport back and crash server

### ISSUE THREAD

**Issue by Raymer753** [quek04/The-Undergarden#175]
When i go to the undergarden dimension is everything okay, but then when i want to go back to the overworld, the portal instantly takes me back to the undergarden and when i try to put or remove any block the server crash.

I paste the error here if someone can help me, i have some mods and i really don´t know if it´s the mod´s fault or if this error is caused by other mods, i apreciate any posible help here

The log:

https://api.mclo.gs/1/raw/1tFfxB8

I know it´s an aterno server and i also contacted them but also i leave this here in case that you have any solution or idea of the problem, thanks

**Comment by Fooshcookie** [comment]
Unsupported version. Year old. Closing.
