### ISSUE TITLE
Game Crashing

### ISSUE THREAD

**Issue by qnwheeler** [quek04/The-Undergarden#176]
In the beginning, I install this mod into my home server's mod's folder as well as my “.minecraft” mods folder, join my home server, and it was laggy for about 40 seconds until I got the Minecraft dirt screen said saving world and my game crashed entirely. Each time I try to get back into the server, it says "Encrypting", "Joining World", "Saving World" and then my game crashes again with multiple attempts. The server itself does not crash, however. This is a shame because this looks like a great mod.

Also, when I create a single player world with the mod installed in my .minecraft mods folder, it is also laggy as and my game crashes when I place or mine a block, so I remove the mod from both the game's mod folder and the server's mod folder. Luckily, single player mode works fine once I remove the mod out of the “.minecraft” folder. No serious problems yet.

I go to remove the mod from the server's mod folder, and launch the run.batch file, the cmd.exe says I'm missing entities/blocks/items and whatnot from the Undergarden's data pack, which prevents the server startup. No problem, ill just force continue the server startup without the missing entries by typing CONTINUE in the command prompt. But I can't type anything in the server's prompt to force startup without the missing data from this mod when the server isn't starting in the first place.

If you could give me some advice on how to not have my game crash upon joining any world, send me an edited version of the mod that doesn't crash my game when join any world, or show me how to force start my server without the mod installed that would be amazing as I have been loving my server. I'm using forge 1.20.1 on a Windows desktop.

Feel free to email me about this issue to discuss further - qnwheeler@gmail.com, I would be extremely grateful for any help or tips. I had this issue once before with removing a herobrine mod from my server, and since I don't know anything about Java I sent the “cmd.exe” error prompt to the publisher and he was gracious enough to write and send me a version of the mod that didn't give me undesired outcomes but allowed my server to start. If you can’t do that, that's fine but I would appreciate any kind of advice or tips from anyone.  I'm entirely out of options and I must ask for help. Thank you.
P.S. It might be an issue with ram, as I can run my server or a single player world with this mod if its set at 2 chunks, anyone know how to get my ram working better? The server already has 48GB ram allocated, which should be fine even if I do have 36 mods installed.

**Comment by Fooshcookie** [comment]
Logs. Provide logs. We can't do anything without them. Once such is provided, MAYBE we can help. 

We don't do stuff through email, everything can be discussed here. That's the point of the comment system.

**Comment by GizmoTheMoonPig** [comment]
When opening an issue regarding any mod, you should attach a crash report or the latest.log. Theres literally nothing we can do help otherwise. Since you said only your client is crashing, I would appreciate a crash report or latest.log thats on your machine. The server wont provide any info in this crash. 
Also for the love of god dont dedicate 48 gigs of RAM to a server with 36 mods. You only need 4 at best

**Comment by qnwheeler** [comment]
Here's the exit code: 
[The game crashed whilst exception w.txt](https://github.com/quek04/The-Undergarden/files/14046370/The.game.crashed.whilst.exception.w.txt)

Here's the Crash report:
[crash-2024-01-24_19.19.04-client.txt](https://github.com/quek04/The-Undergarden/files/14046373/crash-2024-01-24_19.19.04-client.txt)

Here's the latest.log:
[latest.log](https://github.com/quek04/The-Undergarden/files/14046376/latest.log)

Thank you guys for helping me out within an hour of me posting. As you would assume, I'm new to this and any information is huge for me as a server owner and I appreciate your time and any advice you guys might have for me. Please let me know if I can send over anything else that will help me.

Cheers

**Comment by qnwheeler** [comment]
Also I might as well add that the game crashed right as I punched an Enderman, if that helps.

**Comment by GizmoTheMoonPig** [comment]
The crash log you linked was caused by the mod extra gore. They arent correctly adding particles to the game so when the particle engine tries to call for the particles the game crashes as textures arent defined. Of course the mod doesnt have an issue tracker or a github so I dont have an easy way of reporting this. I would just remove the mod for now as punching anything that can spawn their blood particles will crash the game.

**Comment by qnwheeler** [comment]
Lastly, this is the server log when I try to remove the mod from the server as a last resort: 
[latest.log](https://github.com/quek04/The-Undergarden/files/14046546/latest.log)

**Comment by qnwheeler** [comment]
> The crash log you linked was caused by the mod extra gore. They arent correctly adding particles to the game so when the particle engine tries to call for the particles the game crashes as textures arent defined. Of course the mod doesnt have an issue tracker or a github so I dont have an easy way of reporting this. I would just remove the mod for now as punching anything that can spawn their blood particles will crash the game.

Ill try to remove that mod, that makes so much sense now. You're the best thank you so much.

Cheers

**Comment by GizmoTheMoonPig** [comment]
unfortunately removing dimension mods after loading a world isnt an easy task. You have to open your level.dat and remove all references to the undergarden. 
If you get another crash let me know and send the crash report my way. I'll check it out

**Comment by qnwheeler** [comment]
It seems like everything is working fine now, thanks.
