### ISSUE TITLE
Unable to join server 0.8.11

### ISSUE THREAD

**Issue by mxnmnm** [quek04/The-Undergarden#180]
I get invalid player data when I try to join

Server log:
https://gist.github.com/mxnmnm/ba989fb77b059f0782d9e6226e97ded8

Client log:
https://gist.github.com/mxnmnm/6dc1f1b296b892bcb6c0d8de95b0f778

**Comment by GizmoTheMoonPig** [comment]
curseforge is taking forever to approve files and I dont have access to the modrinth page, but there will be a new upload soon that will fix this. Really sorry about all these issues
