### ISSUE TITLE
Crash on The Undergarden 0.8.10

### ISSUE THREAD

**Issue by dheivs** [quek04/The-Undergarden#182]
Hello! 

I'm an avid fan of the mod here for 2 years ^_^

After updating from version 0.8.9 to 0.8.10, I can't run my Minecraft.

Here's the [crash report](https://pastebin.com/BJjjU4p8).

**Comment by TysonTheEmber** [comment]
net.minecraftforge.fml.ModLoadingException: The Undergarden (undergarden) encountered an error during the common_setup event phase
§7java.lang.NoSuchFieldError: STEP_HEIGHT

**Comment by GizmoTheMoonPig** [comment]
see #181
