### ISSUE TITLE
1.20.1 Last Update Crash

### ISSUE THREAD

**Issue by xd4rkzghost01** [quek04/The-Undergarden#183]
Hi ! I was building up a personal modpack (download 1by1 all mod i want to play)
and the last update of this mod seem not working.

Minecraft 1.20.1
Forge 47.2.18
Undergarden 0.8.10
[UndergardenLast.log](https://github.com/quek04/The-Undergarden/files/14308781/UndergardenLast.log)

Downgrade to 0.8.9 seem working fine, but i see there a lot of change with the last update and i'd love to try them.

**Comment by Daltaxy** [comment]
+1
[crash-2024-02-16_10.15.01-client.txt](https://github.com/quek04/The-Undergarden/files/14308890/crash-2024-02-16_10.15.01-client.txt)

everything worked fine yesterday

`Error: net.minecraftforge.fml.ModLoadingException: The Undergarden (undergarden) encountered an error during the common_setup event phase`

**Comment by FrozenGalaxy** [comment]
Also leftover client code that is not guarded on server:
https://gist.github.com/FrozenGalaxy/6fa37ebfc7c081ae7d559f0839bd523f

**Comment by uhloin** [comment]
my dump
[crash-2024-02-16_15.36.32-client.txt](https://github.com/quek04/The-Undergarden/files/14310524/crash-2024-02-16_15.36.32-client.txt)

**Comment by GizmoTheMoonPig** [comment]
See #181. 
Guys, this has been reported like 6 times already. We've fixed the issue, curseforge is just taking forever to approve the file. Please look at other issue tickets before opening new ones, there aren't many in this repo
