### ISSUE TITLE
Smogstem saplings grow Wigglewood trees

### ISSUE THREAD

**Issue by Tapirking1** [quek04/The-Undergarden#19]
![Smogstem sapling](https://user-images.githubusercontent.com/62407700/89483120-540e9080-d769-11ea-9aed-18543c15a646.png)
Smogstem Sapling
![Wigglewood Tree](https://user-images.githubusercontent.com/62407700/89483217-85875c00-d769-11ea-8cc7-87b8a5543caf.png)
Wigglewood Tree

**Comment by quek04** [comment]
OH MY GOD YOURE RIGHT

**Comment by quek04** [comment]
WHAT THE HELL

**Comment by quek04** [comment]
fixed
