### ISSUE TITLE
Crash when making a new world.

### ISSUE THREAD

**Issue by SmartStreamLabs** [quek04/The-Undergarden#192]
Server crash when making / loading a new world.

Mod:

The_Undergarden-1.20.6-0.8.18
[crash-2024-07-08_15.17.28-client.txt](https://github.com/user-attachments/files/16128962/crash-2024-07-08_15.17.28-client.txt)

Hope i could help!

**Comment by Fooshcookie** [comment]
I'll bring it up to the team.

**Comment by GizmoTheMoonPig** [comment]
found the issue, will push out a hotfix for this soon. This was unfortunately a porting error
