### ISSUE TITLE
Add Armour Tags to Ancient Armour

### ISSUE THREAD

**Issue by TheBedrockMaster** [quek04/The-Undergarden#195]
Add forge armour item tags to Ancient Armour, for example add the `forge:armors/helmets` tag to the Ancient Helmet, etc.

**Comment by Fooshcookie** [comment]
Please post your game version, modloader version and mod version.

**Comment by GizmoTheMoonPig** [comment]
the armors have been added to the proper tags in 1.21. Older versions are now unsupported, but you can very easily add the items yourself with a datapack if you need them in the tags for some reason

**Comment by TheBedrockMaster** [comment]
Thanks
