### ISSUE TITLE
[1.16.5 Bug] Effect Brittleness deal strange damage

### ISSUE THREAD

**Issue by GoldenTotem** [quek04/The-Undergarden#199]
Minecraft 1.16.5 Forge 36.2.35 Mod 0.5.5

Brittleness effect will deal an extra ( generic.armor + effect.amplifier + 1 ) damage, but this damage doesn't like a normal damage, it cannot be absorped by armor, protection enchantment, and resistance effect, even absorption effect, is it use setHealth() ?

1. Enter a world and summon a husk.
2. Run `/effect give @e[type=!player,sort=nearest,limit=1] minecraft:resistance 30 4`
3. Run `/effect give @e[type=!player,sort=nearest,limit=1] minecraft:absorption 30 9`
4. Run `/effect give @e[type=!player,sort=nearest,limit=1] undergarden:brittleness 30 0`
5. Attack it, and use neat mod or /data to check it health, it lost 3 health.

It should not lost health, but absorption and resistance doesn't work yet.

Expected:
The extra "damage" should be a normal damage and can be absorped by armor, protection and etc.

**Comment by quek04** [comment]
1.16.5 is unsupported

**Comment by Fooshcookie** [comment]
That version is both unsupported and way outdated. In addition to me not fully understanding what you mean, I regret to inform you that we will not be updating or changing said version at all, anymore. ⇒ https://github.com/quek04/undergarden/issues/170 

For a more complete Undergarden experience, please try playing newer versions such as 1.20/21. That is where our most recent and higher quality updates will be, in addition to any future support for the mod. Closing this issue.

Cheers,
Fishcookie [Undergarden Team]

**Comment by GoldenTotem** [comment]
This problem is caused by using [LivingDamageEvent](https://github.com/quek04/undergarden/blob/126c4747d09a204c6c7ad2558acec615ba0baf72/src/main/java/quek/undergarden/potion/BrittlenessEffect.java#L20) instead of LivingHurtEvent.

**Comment by quek04** [comment]
ok, i guess
