### ISSUE TITLE
Alpha 0.2.2 The Stoneborn breaks blocks when gamerule mobGriefing false

### ISSUE THREAD

**Issue by aarter180** [quek04/The-Undergarden#20]
In 0.2.2 Alpha for 1.16.1 that just added the Stoneborn, it seems they have some kind of explosive attack and it breaks blocks even when the gamerule mobGriefing is set to false, which I expected not to happen.  
This can be recreated by having the Stoneborn attack anything (such as Rotspawn) and see if the explosion breaks blocks when mobGriefing is set to false.

**Comment by quek04** [comment]
uh, stoneborn don’t have explosive attacks?

**Comment by quek04** [comment]
i assume you meant it still damages blocks when exploding after being in the overworld, which i have fixed. closing

**Comment by aarter180** [comment]
Oh, I didn’t make the connection somehow.  I only tried it in the overworld yes.
