### ISSUE TITLE
Blisterberries, Ditchbulbs and Underbeans do not regrow

### ISSUE THREAD

**Issue by AmberGoop** [quek04/The-Undergarden#203]
MC Version: 1.21.1
Mod version: 0.8.21
NeoForge version: 21.1.62

as title says, "bush"-type crops do not regrow.
tested by planting all three right next to a torch and setting randomTickSpeed to 3000.
none of them progressed even a single growth stage.
Gloomgourds are not affected by this, and grow normally.

**Comment by Fooshcookie** [comment]
Ermmmmmmm. No?
