### ISSUE TITLE
Have to use Stone Bricks , not ( stone )

### ISSUE THREAD

**Issue by conetopia** [quek04/The-Undergarden#209]
https://www.curseforge.com/minecraft/mc-mods/the-undergarden
Description Said :

create a frame in the shape of a Nether portal using Stone or Deepslate Bricks.

Apparently its not ( Stone ) , its Stone Bricks.

Good thing there was a picture included.

**Comment by Fooshcookie** [comment]
Okay, so we're gonna do this:

We're going to close this, as it has been noted. We can change it later, but this is a reading comprehension issue, not something that is wrong with the mod. 

Stone Bricks are intentional.

**Comment by quek04** [comment]
The description of the mod has been updated to avoid this problem
