### ISSUE TITLE
Forge Mod Loader support?

### ISSUE THREAD

**Issue by txj-xyz** [quek04/The-Undergarden#22]
Will this mod be compatible with Forge?

**Comment by quek04** [comment]
uh... it _is_?

**Comment by txj-xyz** [comment]
*cough* additinyourreadme *cough*

**Comment by quek04** [comment]
![image](https://user-images.githubusercontent.com/55364841/89968170-c7f0e300-dc18-11ea-8ecc-a1665133075e.png)
im afraid that you're blind

**Comment by txj-xyz** [comment]
Sorry mate, I don't see that anywhere

![](https://i.txj69.xyz/YaeIwro6TQ.png)
