### ISSUE TITLE
Portal doesn’t work

### ISSUE THREAD

**Issue by HugoMage** [quek04/The-Undergarden#23]
I’m using the newes version of your mod that I found on curseforge and the Minecraft version is 1.16.1 the mod worked and everything but the portal to the dimension didn’t I lite it up and it shows portal blocks but when I go through it nothing happens I tried starting the portal with me inside the portal but it just crashes my game

**Comment by Mysticpasta1** [comment]
I'm having the same issue everything works but going inside the portal doesn't take you to the dimension it just lets you stand there.
