### ISSUE TITLE
Incompatibility with Immersive Portals

### ISSUE THREAD

**Issue by magolor88** [quek04/The-Undergarden#24]
It seems as though the dimension does not appear in the mod's dimension wrapping feature. Seeing as this is an underground cavern mod, I think it would be very cool to have the option to place the dimension under the overworld.

**Comment by rayquaza8084** [comment]
What versions are you playing on? I am on mc 1.15.2, forge-31.2.36, and undergarden 0.1.5 and doing the dimension stack feature without a problem.

**Comment by MisterBurgerBeachball1225** [comment]
I'm having the same issue as OP, and I'm on:

Minecraft: 1.16.1
Forge: 32.0.108
Immersive Portals: 0.2 (Even though in the in-game mods list it says 0.1?)
Undergarden: 0.2.3

**Comment by JulianPlusPlus** [comment]
immersive portals isn't supported for the 1.16.1 version of the mod, however the 1.15 version is

**Comment by MisterBurgerBeachball1225** [comment]
It's unfortunate that things must always be this way. Oh well, these things happen when you've got an infinitely-progressing game like Minecraft. As the old saying goes, progress waits for no man.

**Comment by JulianPlusPlus** [comment]
he'll probably work on compatibility once he comes out with the 1.16.2 port lol

**Comment by quek04** [comment]
mod compatibility isnt an issue.
