### ISSUE TITLE
Single Player/Server Freezing in Undergarden

### ISSUE THREAD

**Issue by Darkfiend009** [quek04/The-Undergarden#25]
Minecraft: 1.16.1
Forge: 32.0.108
The Undergarden: 0.2.3

When traversing The Undergarden, eventually the server (or client in a single player world) will stop loading chunks and when looking at a block/entity will say "Waiting for server." You have to kill the client or server as it hangs forever.

I included my latest.log to show what is happening while in The Undergarden.

latest.log: https://gist.github.com/Darkfiend009/b99da174f763cfacdf347a071cc772af

**Comment by quek04** [comment]
your log is full of errors that aren't related to the undergarden. this probably isnt my fault.
