### ISSUE TITLE
Forge compatibility?

### ISSUE THREAD

**Issue by theanimator88** [quek04/The-Undergarden#27]
Will you be making this mod compatible with forge? My friends and I tried to get this mod working on our forge server, the portal appears but doesn't work. Same problem the last guy had. Wondering if you're working on making it compatible, and if so do you have an ETA? Thank you very much, have a good one.

**Comment by quek04** [comment]
uh... the mod _is_ for forge?

**Comment by quek04** [comment]
the portal issue is a serverside forge problem. there's nothing i can do about it. stop asking.
