### ISSUE TITLE
Portal doesnt work on 1.16.1 multiplayer

### ISSUE THREAD

**Issue by Flosenox** [quek04/The-Undergarden#28]
Me and my friend decided to go to the dimension and when made the portal, it just wont teleport us, will this be fixed??

**Comment by CarJohn38** [comment]
no because its forge not the mod

**Comment by Flosenox** [comment]
well thats stupid, probably the only dimension mod on this version for now,  and it doesnt work properly on multiplayer xD

**Comment by CarJohn38** [comment]
welcome to forge
