### ISSUE TITLE
Undergarden in The End

### ISSUE THREAD

**Issue by joelmoli** [quek04/The-Undergarden#29]
The  Undergarden mobs and ambient mixes with The End Please Fix this is so annoying

![ERROR](https://user-images.githubusercontent.com/70319569/91422878-0f51b300-e858-11ea-82d3-0bbe76917ea6.png)

**Comment by quek04** [comment]
I'm sorry, what?

**Comment by JulianPlusPlus** [comment]
I wonder if other mods are causing this or something

**Comment by quek04** [comment]
if you're not going to give any further information i'm closing this.
