### ISSUE TITLE
Bonemeal functionality

### ISSUE THREAD

**Issue by MightyGoat4242** [quek04/The-Undergarden#3]
Bonemeal generates normal seaweed on depthrock and deepsoil, and deepturf blocks can be bonemealed, but it just uses the bonemeal makes the green particles appear in the deepturf block, it doesn't generate any plants.

**Comment by quek04** [comment]
I don't think I can prevent the bone meal from creating normal sea grass. I just pushed a fix that stops you from bone mealing Deepturf.
