### ISSUE TITLE
Undergarden biomes spawning in overworld

### ISSUE THREAD

**Issue by PrimBee** [quek04/The-Undergarden#32]
I'm using forge for 1.16.1, and I've noticed spots of the undergarden spawning all over the overworld. I'm also using biomes O' plenty, in case that has anything to do with it.
![2020-09-06_14 52 48](https://user-images.githubusercontent.com/70860949/92334177-7fbeb800-f040-11ea-8c9f-d43ded40d374.png)
![2020-09-06_14 52 58](https://user-images.githubusercontent.com/70860949/92334178-80574e80-f040-11ea-8b53-ff9c66be6172.png)
![2020-09-06_14 52 16](https://user-images.githubusercontent.com/70860949/92334180-80574e80-f040-11ea-8a84-e00d96824571.png)
![2020-09-06_14 55 45](https://user-images.githubusercontent.com/70860949/92334295-679b6880-f041-11ea-90ab-b907cd22bb41.png)
![2020-09-06_15 00 20](https://user-images.githubusercontent.com/70860949/92334296-6833ff00-f041-11ea-902c-ac2c9ab965a2.png)

**Comment by quek04** [comment]
That might be caused by BoP or some other world gen mod you might have installed. I don't touch the Overworld's generation in the slightest.
