### ISSUE TITLE
Crash with the Voxelmap

### ISSUE THREAD

**Issue by dheivs** [quek04/The-Undergarden#36]
Every time I open and close the Voxelmap while inside the Undergarden, it crashes.  Here's the crash log:

[crash-2020-10-31_23.45.15-client.txt](https://github.com/quek04/The-Undergarden/files/5469360/crash-2020-10-31_23.45.15-client.txt)

**Comment by quek04** [comment]
This is probably a problem with VoxelMap - should report it to them.
