### ISSUE TITLE
[1.16.3] Failed to load description for particle

### ISSUE THREAD

**Issue by Rumaruka** [quek04/The-Undergarden#38]
Minecraft: 1.16.3
Forge: 34.1.35
Mod Version: 0.3.6
Crashlog: https://pastebin.com/Vi81ntc9

**Comment by quek04** [comment]
Not sure what to make of this, sorry. Might be another mod causing it.

**Comment by qwertyuiopkl556** [comment]
I got this same problem too
It's from the Ratlantis mod

**Comment by quek04** [comment]
Closing this since it's been a month.
