### ISSUE TITLE
missing textures

### ISSUE THREAD

**Issue by Npcfanatic21** [quek04/The-Undergarden#4]
in the creative inventory, 4 wall blocks are missing textures:
cobbled depthrock wall
depthrock brick wall
cobbled shiverstone wall
shiverstone brick wall

![2020-06-30 17_40_08-Minecraft_ 1 15 2 - Singleplayer](https://user-images.githubusercontent.com/25681027/86184222-52620500-baf9-11ea-80b3-51ba2aadd84a.png)

**Comment by quek04** [comment]
you're right! this has plagued me for months.

**Comment by quek04** [comment]
it's finally fixed! closing.
