### ISSUE TITLE
[1.16.4] The Undergarden prevents Thermal Series Phyto-Soil from being tilled by hoes.

### ISSUE THREAD

**Issue by tplc10** [quek04/The-Undergarden#43]
Relevant Mod versions: 

- Thermal Cultivation 1.0.5
- The Undergarden 0.3.8
- Forge 35.1.7

**Comment by quek04** [comment]
Folks in my discord reported that Thermal Series is closed source which makes this issue practically impossible to figure out the cause of.

**Comment by tplc10** [comment]
Are you sure? I found [this page](https://github.com/KingLemming/1.16) which looks like the right one

**Comment by KingLemming** [comment]
That's absolutely the right page, yes. I add my blocks to the HOE_LOOKUP table and that is literally it.

What are you doing with hoes that could possibly break this behavior?

**Comment by quek04** [comment]
I do that too! So I don't know :(

**Comment by quek04** [comment]
![image](https://user-images.githubusercontent.com/55364841/102931357-df13cd00-4463-11eb-8870-c2e524b0187c.png)

**Comment by KingLemming** [comment]
No... You are literally overwriting the entire map with your own.

**Comment by quek04** [comment]
oh

**Comment by KingLemming** [comment]
This is what I'm doing. Presumably you need to do a putAll instead and provide your map.

`HoeItem.HOE_LOOKUP.put(BLOCKS.get(ID_PHYTOSOIL), BLOCKS.get(ID_PHYTOSOIL_TILLED).getDefaultState());`

**Comment by KingLemming** [comment]
Or, add your 3 blocks individually if it's just 3. Seems simple enough. :)

**Comment by quek04** [comment]
ty for enlightening me

**Comment by quek04** [comment]
i will fix this soon

**Comment by KingLemming** [comment]
Sure thing :) Thanks for the quick fix!

**Comment by KingLemming** [comment]
You're also doing the same thing with AXE_STRIPPING, just a heads up. You'll want to change that too.

**Comment by quek04** [comment]
`AxeItem.BLOCK_STRIPPING_MAP.put(UGBlocks.SMOGSTEM_LOG.get(), UGBlocks.STRIPPED_SMOGSTEM_LOG.get());
		AxeItem.BLOCK_STRIPPING_MAP.put(UGBlocks.SMOGSTEM_WOOD.get(), UGBlocks.STRIPPED_SMOGSTEM_WOOD.get());
		AxeItem.BLOCK_STRIPPING_MAP.put(UGBlocks.WIGGLEWOOD_LOG.get(), UGBlocks.STRIPPED_WIGGLEWOOD_LOG.get());
		AxeItem.BLOCK_STRIPPING_MAP.put(UGBlocks.WIGGLEWOOD_WOOD.get(), UGBlocks.STRIPPED_WIGGLEWOOD_WOOD.get());
		AxeItem.BLOCK_STRIPPING_MAP.put(UGBlocks.GRONGLE_STEM.get(), UGBlocks.STRIPPED_GRONGLE_STEM.get());
		AxeItem.BLOCK_STRIPPING_MAP.put(UGBlocks.GRONGLE_HYPHAE.get(), UGBlocks.STRIPPED_GRONGLE_HYPHAE.get());

		HoeItem.HOE_LOOKUP.put(UGBlocks.DEEPTURF_BLOCK.get(), UGBlocks.DEEPSOIL_FARMLAND.get().getDefaultState());
		HoeItem.HOE_LOOKUP.put(UGBlocks.DEEPSOIL.get(), UGBlocks.DEEPSOIL_FARMLAND.get().getDefaultState());
		HoeItem.HOE_LOOKUP.put(UGBlocks.COARSE_DEEPSOIL.get(), UGBlocks.DEEPSOIL.get().getDefaultState());`

**Comment by quek04** [comment]
well that didnt format properly

**Comment by quek04** [comment]
nvm i don't know how to fix this

**Comment by KingLemming** [comment]
Huh? No you were doing it right. It looked fine!

**Comment by KingLemming** [comment]
Have you addressed this yet? The code that you posted would have worked just fine.
