### ISSUE TITLE
oppening voxel map crash game warning!

### ISSUE THREAD

**Issue by FurryApocalypse** [quek04/The-Undergarden#45]
Hi there. Im using forve version of voxel map  (1.10.12 for 1.16.4) and untill i play without oppening it - there is everything fine.
But when you open the voxel map it couse crash in undergarden dimension.
Not rly and issue of the mod itself i think. I place it here as a warning.

**Comment by JulianPlusPlus** [comment]
go report it to voxel, it's probably not our fault

**Comment by FurryApocalypse** [comment]
> go report it to voxel, it's probably not our fault

Thanks for that quick answer. I will do it right away!

**Comment by JulianPlusPlus** [comment]
cool

**Comment by FurryApocalypse** [comment]
Seems like voxel itself makes problems and crashes so we can close this one. Thanks for cooperation!
