### ISSUE TITLE
Cannot mine depthrock

### ISSUE THREAD

**Issue by torterra2234** [quek04/The-Undergarden#46]
Currently unable to mine depthrock with a tetra pickaxe.

Pickaxe is capable of mining obsidian itself, but nothing drops when used on depthrock, using a regular diamond pick works correctly , as does using a tetra shovel on the undergarden soil, it's only the rock (and ores in said rock) that this appears to affect. confirmed using a minimal set of most recent versions:

jei-1.16.4-7.6.0.58 (used to cheat things in)
mgui-1.16.4-3.1.3 (tetra dependency)
tetra-1.16.4-3.3.1
The_Undergarden-1.16.3-0.3.8
minecraft 1.16.4
forge 35.1.7

pickaxe spec: 2 blackstone heads

**Comment by quek04** [comment]
🤷

**Comment by shutdoor** [comment]
Tetra tools don't seem to allow for the mining of items in The Undergarden. If you use a normal vanilla tool you will be fine.

**Comment by quek04** [comment]
after seeing the issue in a youtube video, it seems like tetra tools don't have proper mining levels or something.
probably isn't my fault
