### ISSUE TITLE
The portal wont even start / open, how do I fix this?

### ISSUE THREAD

**Issue by Teego2214** [quek04/The-Undergarden#47]

**Comment by ghost** [comment]
could you.. specify? did you install the mod? what are you trying to do, exactly? how'd you try to open the portal? what did you make the portal out of? what other mods do you have installed, if any, and what version are you playing on / what version of the undergarden do you have installed?

**Comment by Teego2214** [comment]
you see, yes i have installed the mod and it is somewhat working because i was able to craft the catalyst, i was making sure all the mods were working good, i used the catalyst on a stone brick portal by right clicking on the inner bottom of the portal frame, stone brick. the conjurer, towers of the wild, structure gel-api, structurise Alpha, shrink. 1.16.4 and im playing on 1.16.3-0.3.8.jar which is suposedly compatable with 1.16.4

**Comment by ghost** [comment]
then i don't know what's wrong, and this is where my knowledge of anything ends.
but now that you've actually provided us with information, someone else might be able to help here, apologies. it might be a conflict with one of those mods

**Comment by Teego2214** [comment]
Thats ok, Thanks though

**Comment by quek04** [comment]
refer to issue #16

**Comment by Teego2214** [comment]
Its on a private single player world, nothing to do with a server or such

**Comment by quek04** [comment]
Are you _certain_ you're using specifically stone bricks, depthrock bricks, or shiverstone bricks? make sure you aren't using infested stone bricks on accident.

**Comment by Teego2214** [comment]
i might have been, just loaded it back up alone and made sure i didnt use infested bricks and it worked
