### ISSUE TITLE
Multiple Mod issue

### ISSUE THREAD

**Issue by steliosagge** [quek04/The-Undergarden#51]
Im trying to make mobs from other mods spawn in the undergarden but i cant no matter what, i whitelist the dimension ID or tampered with configs to make each mob individually spawn and still doesnt work, soo.. is it blocked for the mod configuration? (cant find a configuration to tamper with either) i dont know i just need some help on how to do so. (1.16.4)

**Comment by quek04** [comment]
don't see how this would be my fault at all, sorry.
