### ISSUE TITLE
[1.16.4] Diamond Ore Too Common

### ISSUE THREAD

**Issue by NielsPilgaard** [quek04/The-Undergarden#54]
Diamond Ore is far more common in the Undergarden than in the overworld, I estimate roughly 8 times as common. Is this intended, and if not, could it be toned down a bit please? :)

Original issue: https://github.com/NillerMedDild/Enigmatica6/issues/669

**Comment by quek04** [comment]
this is fixed in 121d0ba1e64c28ce18535be47a03c12d0fcefa79

**Comment by NielsPilgaard** [comment]
Ah nice, thanks :) I think 3 might be a bit high still, but definitely better.
