### ISSUE TITLE
overworld music in the undergarden

### ISSUE THREAD

**Issue by Omega58** [quek04/The-Undergarden#56]
hello,i have an issue with the mod  
undergarden music doesn't play, overworld music does instead

this happens in creative,i have no idea if this happens in survival 
i have this problem in both 1.16.1 and .16.14,i know that you don't support 1.16.1 anymore,but the issue seems to never been fixed before.
(i am uisng the latest release)
(sorry for the bad english)

**Comment by quek04** [comment]
this only happens in creative, it isn't worth fixing.

**Comment by Omega58** [comment]
i'll see if this also happens in survival
