### ISSUE TITLE
Feature Request: In-Game Book/Manual with Tutorial/Wiki Info

### ISSUE THREAD

**Issue by Danekjovax** [quek04/The-Undergarden#59]
Please add an item in-game to show one the basics of this great mod.  It's only the logical thing to do.  Thanks.

**Comment by quek04** [comment]
A wiki is being worked on.
https://the-undergarden-mod.fandom.com/wiki/The_Undergarden_Mod_Wiki

**Comment by Danekjovax** [comment]
Much appreciated for the quick response, but will this be in-game?  It's not very immersive when you always have to leave the game screen to figure out something as basic as making the portal.

**Comment by quek04** [comment]
The instructions on making a portal are on the curseforge page...

**Comment by Danekjovax** [comment]
You obviously don't get my point.  Well, it was a request.  Thanks anyways.
