### ISSUE TITLE
Not really an issue, but does this mod use biome dictionary?

### ISSUE THREAD

**Issue by mosharky** [quek04/The-Undergarden#62]
I want to add mobs from a mod I've been using into the dimensions this mod adds, but I need to give said mod a biome dictionary tag or whatever. Thanks.

**Comment by quek04** [comment]
Yes, as of 0.4.1 the Undergarden biomes are included in the Forge biome dictionary. Or at least, they should be...

**Comment by reetamb** [comment]
look at this link if you need to see what biome dicts each biome is https://github.com/quek04/The-Undergarden/blob/1.16/src/main/java/quek/undergarden/registry/UGBiomes.java

**Comment by mosharky** [comment]
oh okay, thanks! I had no idea how to check :P
