### ISSUE TITLE
Clouds in the Undergarden

### ISSUE THREAD

**Issue by LiskoSlayer63** [quek04/The-Undergarden#63]
This is a very minor bug, but the clouds are generated in the Undergarden. It looks kinda funny, but it's still a bit odd, especially when I assume the Undergarden is underground world like the Blackreach.

**Undergarden version:** 0.3.8
**Forge version:** 35.1.13

**Screenshot:**
![2021-01-07_05 00 08](https://user-images.githubusercontent.com/10125529/103848087-4491cb80-50aa-11eb-82bc-4712b59c3a3b.png)

**Comment by quek04** [comment]
why is the sky orange?

**Comment by LiskoSlayer63** [comment]
@quek04 Actually very good question, I don't know. I think it's related to OptiFine, render distance and maybe dimension stack by Immersive Portals. Nether is under the Undergarden and the Undergarden is under the Overworld, this might affect the appereance of the sky colors? There's no clouds in the nether still and Y-axel resets everytime you dig through the dimension border.

**Comment by quek04** [comment]
Do you have Immersive Portals? I have a feeling it might cause that

**Comment by LiskoSlayer63** [comment]
@quek04 Yes I do. I can open an issue to them instead if the problem persists.
