### ISSUE TITLE
{Enhancement} Support for Silent Gear, please?

### ISSUE THREAD

**Issue by AbsorbingSafe11** [quek04/The-Undergarden#64]
1) Silent Gear is a mod for Minecraft 1.16.4 that allows the production (by players) of tools made out of different materials and take on traits of the materials used in each tool part. (similar to Tinkers, but better and more vanilla friendly)
2) I would like to be able to use Undergarden materials to make such tools, but I don't know how to properly balance the tools or materials from the Undergarden, so the aren't overpowered or underpowered. (also, I am unable to code and stuff)
3) Could you please add support for using Undergarden materials to Silent Gear so I can make tools using stuff I gather from the Undergarden.
4) CurseForge link to Silent Gear (https://www.curseforge.com/minecraft/mc-mods/silent-gear)
5) Thank you for reading, and I hope it is possible to add. (if not, it is also fine)

**Comment by quek04** [comment]
I personally have no interest in putting effort into making compatibility with a mod I've never used.
It can probably be done,  but not by me!

**Comment by StrangerSon71** [comment]
@AbsorbingSafe11 There is a Tetra addon for The Undergarden, you should check it out. It is superior to Silent Gear IMO.

**Comment by AbsorbingSafe11** [comment]
Anyone who wishes to comment on this closed issue, please read the original first.
 (also Tetra doesn't add armor, so it is de facto worse)

**Comment by StrangerSon71** [comment]
I read the original. The armor is a fair point, waiting till it adds armor (Or just enjoying the ability to use fancy unique Alex's Mobs armor pieces) is a reasonable stance.
