### ISSUE TITLE
The undergarden overwrote other dimensions

### ISSUE THREAD

**Issue by shutdoor** [quek04/The-Undergarden#65]
I am playing in the Direwolf20 1.16, and it seems the newest version of the Undergarden has overwritten the Void Dimension from Just Another Void Dimension mod & Just Another Mining Dimension. This might carry over to other Dimension mods I am not sure. I've checked and the nether is fine.

This is mod version 0.4.2

**Comment by willrun4fun** [comment]
Same issue, ticket on the FTB board https://github.com/FTBTeam/FTB-Presents-Direwolf20-1.16/issues/99

**Comment by JulianPlusPlus** [comment]
are you running the latest version of forge?

**Comment by UnRealDinnerbone** [comment]
The Forge is the lastest 35.1.36

**Comment by UnRealDinnerbone** [comment]
The same thing happens in JAVD (Just Another Void Dimension) but with a different biome "SmogStem Forest" don't think it my issue since Im loading both dimensions with pure json and all the code does handle the teleports.

**Comment by quek04** [comment]
this isn't an issue with the mod, it's a vanilla issue. closing
