### ISSUE TITLE
JAMD and The Undergarden bug

### ISSUE THREAD

**Issue by kienee** [quek04/The-Undergarden#66]
Hey,

I've been playing the FTB Direwolf20 1.16 Modpack (newest  version) with JMAD 1.1.4 and The Undergarden 0.4.2.
The JMAD was working finde :) it was a normal Biom always Day. But as soon as i made an Undergarden Portal and went to the undergarden the Biom of the JMAD Dimension changed to one of the Undergarden . I dont mind it but i think its a Bug :).
Here's a Screenshot.
![2021-01-11_12 24 51](https://user-images.githubusercontent.com/77178672/104176989-57890080-5408-11eb-82c0-cec528ca1329.png)

**Comment by quek04** [comment]
https://github.com/FTBTeam/FTB-Presents-Direwolf20-1.16/issues/99
