### ISSUE TITLE
Apex hosting, biomes o plenty not working with this mod, anyone know how to fix?

### ISSUE THREAD

**Issue by Fordonic** [quek04/The-Undergarden#67]
Hello, so I host a apex hosting server with my friends, and I've tried in single player loading this mod along with biomes o plenty, it doesn't work. Which would mean it won't work on the apex hosting server, does anyone know how to fix this?

**Comment by quek04** [comment]
what do you mean it "doesn't work?" i'm going to need more info

**Comment by JulianPlusPlus** [comment]
forge version and UG version?

**Comment by Fordonic** [comment]
I'm so sorry, I didn't mean to open a ticket on this mod, this mod works fine with my world, I was having issues with another mod sorry for the bothers.

**Comment by quek04** [comment]
lol ok
