### ISSUE TITLE
Crash When a Pepple is shot by the Slingshot

### ISSUE THREAD

**Issue by Maxi90909** [quek04/The-Undergarden#69]
https://pastebin.com/AgkyRt7p

I just used the slingshot and It crashed

**Comment by Maxi90909** [comment]
By the way I can't join My World Anymore please fix

**Comment by quek04** [comment]
this looks like it might be an issue with the undefeatables mod?

**Comment by quek04** [comment]
this isn't going anywhere obviously..

**Comment by reetamb** [comment]
pepple
