### ISSUE TITLE
Portal bug?

### ISSUE THREAD

**Issue by GhostOfTheAshes** [quek04/The-Undergarden#70]
every time i enter and exit the same portal it opens a new portal in a different location filling the area with portals

**Comment by quek04** [comment]
are you on 0.4.3? i attempted to solve this issue in that update

**Comment by GhostOfTheAshes** [comment]
i am on 0.4.3

**Comment by Opherus** [comment]
This bug still seems to exist, no matter where the portals are placed they refuse to connect to the original portal and will instead create entirely new ones every time. (happens both in the overworld and the undergarden)
I am on 0.4.4 and am still getting this bug, will test in more worlds later to see if it could be something with the fact that i installed the mod after generating the world.

**Comment by quek04** [comment]
This issue is odd because every time I've tested the portal it works perfectly fine.....

**Comment by quek04** [comment]
@GhostOfTheAshes What Forge version are you using? Another user in the discord reported that this issue stopped occurring after they updated to the latest version of Forge.

**Comment by GhostOfTheAshes** [comment]
i think its been working now it worked properly on my server when i tried today

**Comment by GhostOfTheAshes** [comment]
im using forge 1.16.5 36.0.1

**Comment by Sniffity** [comment]
quek - reporting further on this. Have done more testing and updating the Forge version to 35.1.37 seems to solve the issue, with one exception:

IF your Overworld portal is made out of Undergarden bricks (not stone bricks), it will not apparently not register the Overworld portal as an actual portal and create a new, stone bricks portal very close to the location of the entry portal made out of Undergarden materials. As it stands, a portal made out of Undergarden materials works as an "entry portal" but not as an "exit portal", apparently.

**Comment by quek04** [comment]
The block you make the portal out of shouldn't matter. The code looks for the portal itself, not what it's made of. When going into the Undergarden the game generates a Stone Brick portal though, regardless of what you made yours with.
