### ISSUE TITLE
Unknown crash when attempting to light up portal

### ISSUE THREAD

**Issue by Sniffity** [quek04/The-Undergarden#72]
Uploading crash report. This might have something to do with DynMap and The Undergarden, maybe?

[Crash_UG.txt](https://github.com/quek04/The-Undergarden/files/5846734/Crash_UG.txt)

**Comment by quek04** [comment]
Try without DynMap?

**Comment by Sniffity** [comment]
Reporting further on this crash: 
- I created a new world for testing, immediately built a portal to the Undergarden and proceeded to crash upon lighting up the portal.
**- Removing DynMap: The crash no longer occurs.. However:**
- I run a server with both DynMap and The Undergarden, and it works just fine, there are no crashes involved when attempting to light up the portal. The two mods are apparently compatible. I do not know what is causing this crash, but whatever it is, does not seem to happen all the time.
- The crash happens when attempting to light up the portal, upon reloading the world the portal has correctly lit up, however.

**Comment by quek04** [comment]
I feel like this isn't a problem with the Undergarden, should probably go show this to the DynMap people?
