### ISSUE TITLE
Undergarden Terrain Generation

### ISSUE THREAD

**Issue by xorgrin** [quek04/The-Undergarden#78]
Had an issue on our Direwolf20 server with undergarden generation so I thought maybe its just our current world or something that was causing the issue so I downloaded a fresh copy of the server of Direwolf20 1.16  1-6-1 and created a portal to the Undergarden. It looks exactly the same as it did on our current server. There are mobs and regular terrain. But I don't see any growth, no ore at all. Here are 2 examples. Based on videos I have seen this isn't how its supposed to look.  
I've found catacombs that contain chests and mobs but other than that its just blocks, no vines, no vegetation at all. 

![2021-02-06_10 35 57](https://user-images.githubusercontent.com/78618804/107122735-7d6abf00-6867-11eb-8343-59556dcfc92d.png)
![2021-02-06_10 36 49](https://user-images.githubusercontent.com/78618804/107122736-7e9bec00-6867-11eb-9cb3-faf911eed4c9.png)

**Comment by quek04** [comment]
does the Direwolf pack contain Immersive Engineering?

**Comment by xorgrin** [comment]
Yes it does, and I apologize because I think this might not be the right place to post originally. I guess I could try removing the immersive engineering and see if that makes it work?

I tested out just the mod on single player and server and its fine. I also posted the issue to the direwolf20 github as well because I wasn't entirely sure what the issue was.

**Comment by Shorepion** [comment]
One player of my modpack also found this conflict (spoiler modlist: https://www.curseforge.com/minecraft/modpacks/magica-infinitum-iii).
https://github.com/Shorepion/Magica-Infinitum-III/issues/9
I made a new world with worldtype "default" and it seemed to fix it. My guess is that there is a conflict with Biomes O' Plenty since its the default worldtype in my modpack.

**Comment by pm065** [comment]
I'm getting this issue on both `default` and `quark:realistic` worldtypes. Neither Apotheosis nor Immersive Engineering are installed, though Psipherals is. Here's the modlist: https://paste.gg/p/anonymous/94df3a21c5e64b68bb7ed636a2154b94

I'm on singleplayer, by the way.
