### ISSUE TITLE
Config Files needed?

### ISSUE THREAD

**Issue by danielmartin0** [quek04/The-Undergarden#79]
Unless I'm misinterpreting things, the update v0.3.1 on 27th October removed config files. But these were necessary to solve https://github.com/quek04/The-Undergarden/issues/9?

**Comment by quek04** [comment]
that was in 1.15, it doesnt really matter anymore. nobody complained about me removing it.

**Comment by danielmartin0** [comment]
I do think there should be a config to remove bedrock in 1.16. This mod would be great with immersive portals, it would be nice for them to be compatible.
