### ISSUE TITLE
0.4.5 seed fix may not entirely work

### ISSUE THREAD

**Issue by Bidgam** [quek04/The-Undergarden#82]
I have 0.4.5 and I entered the portal once, everything checked out, logged in the next day and noticed that there was massive generation cuts exploring beyond the previous boundary.

I exited the dimension and checked my files and noticed that there were no world files after doing so. They were all gone, as if I never created the dimension at all. This 'may' have occurred after shutting down the server just to restart it 'because'.

Using Valhelsia 3 modpack on 1.16.5 and Forge 36.0.15.

**Comment by quek04** [comment]
should be fixed in b7932e0
