### ISSUE TITLE
Undergarden Diamond ore not affected by Botania weight lens

### ISSUE THREAD

**Issue by Paperweight82** [quek04/The-Undergarden#85]
not sure whether this is a botania or undergarden issue, or intended behavior, but all other undergarden ores that generate from the botania orechid fall when hit with a weight lens.
(utherium, otherside utherium and regalium do not fall, but don't generate from the flower either, in this pack at least...)

i'm playing on DW20 1.16 (pack version 1.7.0)
minecraft 1.16.5
mod version is 1.16.5-0.4.5
forge version 1.16.5-forge-36.0.45

forgot to add botania version 1.16.4-441, in case it's needed

**Comment by quek04** [comment]
I don't know anything about Botania so I don't know what that means.

**Comment by Paperweight82** [comment]
i assume the diamond ore behaves like obsidian and that is the problem. thinking about it, it's probably something i should report to the modpack creators rather than the mod author. sorry about that
