### ISSUE TITLE
[Bug] [1.16.4-0.4.5] Description for root advancement displays incorrectly. 

### ISSUE THREAD

**Issue by JoelZBub** [quek04/The-Undergarden#86]
### Bug Description: 
The first advancement shows the name of the localization file rather than a description of the advancement.

### How To Reproduce the Bug:
1. Press 'L' to view advancements
2. Go to The Undergarden tab
3. Hover over first advancement
4. Read description of advancement

### Screenshots
![2021-03-19_13 05 42](https://user-images.githubusercontent.com/12024500/111825445-d8a7bc80-88bd-11eb-83a1-9dc63de4e801.png)

### Additional context:
Forge 1.16.5 - 36.1.1
The Undergarden 1.16.5-0.4.5
Better Advancements 1.16.5-0.1.0.105 is also installed

**Comment by quek04** [comment]
just tested with all the same versions and it doesn't happen. it's some other mod.
![image](https://user-images.githubusercontent.com/55364841/111916296-336d1f80-8a48-11eb-8617-ca2ce0f512eb.png)

**Comment by JoelZBub** [comment]
I guess I'll have to fix it with a data pack then.
![2021-03-21_16 49 45](https://user-images.githubusercontent.com/12024500/111920483-9f11b580-8a65-11eb-94a7-b2ff081a9513.png)

**Comment by JoelZBub** [comment]
This is actually happening because your translate key in the advancement description field
 is blank. It's easily fixed by adding a translation key and then leaving the key's entry blank in the mod's lang file. Alternately, remove the "translate" tag and set the description with a blank string.

Result, even with "conflicting" mod:
![2021-03-21_17 34 01](https://user-images.githubusercontent.com/12024500/111921705-60332e00-8a6c-11eb-831c-84bdc1541b38.png)

**Comment by Tamaized** [comment]
What a lame ass response for a lame ass person.

What translation key, is that mod adding an arbitrary key that doesnt exist in vanilla? How is any mod supposed to be aware of this. Next time instead of being a dick put some effort into being useful.

If this is a vanilla key, then the mod is breaking vanilla behavior. Again not a UG problem.
