### ISSUE TITLE
Blame reported this while loading Undergarden

### ISSUE THREAD

**Issue by pjlasl** [quek04/The-Undergarden#87]
[ERROR] .... [co.te.bl.Blame/]:
****************** Blame Report 1.9.2 ******************
Failed to load structure nbt file from: undergarden:catacombs/way_pool
The path represented by this is: data/undergarden/structures/catacombs/way_pool.nbt
The calling Template Pool is: undergarden:catacombs/catacombs_tunnel6
Most common cause is that there is a typo in this path to the nbt file.
Please let the mod author know about this so they can double check to make sure the path is correct.
A common mistake is putting the structure nbt file in the asset folder when it needs to go in data/structures folder.

**Comment by quek04** [comment]
i don't think this happens anymore
