### ISSUE TITLE
Overworld biomes scrambled after update from 0.4.5 to 0.5.0

### ISSUE THREAD

**Issue by tsheinen** [quek04/The-Undergarden#94]
Hello!  I updated my server from Undergarden 0.4.5 to 0.5.0 and after restarting, we noticed the overworld biomes were scrambled around -- existing biomes were now other biomes. I'm not particularly familiar with how Minecraft handles biomes but what I'm assuming happened is the new version added some biomes and shifted around IDs. I reverted the update without reverting to the world backup and it did fix the biomes. 

I don't really think this is a bug (although what do I know lol), so I suppose mainly what I'm asking is if you know what caused it and if there is a way for us to update without mangling the existing biomes.

**Comment by quek04** [comment]
I didn't add any biomes in 0.5.0.

**Comment by tsheinen** [comment]
Huh, ok, that's really odd. I'll see if I can nail down a minimal replication case.

**Comment by quek04** [comment]
I think this is caused by a vanilla bug, so
