### ISSUE TITLE
Undergarden affects other dimension mod

### ISSUE THREAD

**Issue by Loooser23** [quek04/The-Undergarden#99]
So a few days ago i updated my Undergarden mod from 0.4.5 to 0.5.1 
No issues so far, however the new cleaner textures didnt fit one of my survival builds so i downgraded again to 0.4.5

However now my void world from the JAVD mod (Just Another Void Dimension) is now suddenly located in a undergarden:dense_forest biome.
Now don't get me wrong, the dark green skybox and the 'snow' are very atmospheric, however the sounds are a bit creepy and there is the whole matter of this being absolutely not intended to happen.

I might keep it for a while, though.
Forge is 1.16.5 36.1.17 however there are well over 100 mods installed, all ameteurishly put together. Below is a picture of the phenomenon

![2021-05-18_15 37 35](https://user-images.githubusercontent.com/84392651/118661071-14dc9800-b7ef-11eb-827c-0af92c069de2.png)

**Comment by quek04** [comment]
this is the vanilla biome shifting bug

**Comment by Loooser23** [comment]
thanks for the quick reply. Mind telling me in a few quick words why this happens and how it can be prevented or send a link to info about it? I tried google searching it, but it's not that easy to find.

**Comment by MokahTGS** [comment]
Yeah, this needs some sort of a fix, because the same thing happens to the Atum 2 dimension in some areas.

https://github.com/TeamMetallurgy/Atum2/issues/245

**Comment by Tamaized** [comment]
https://www.curseforge.com/minecraft/mc-mods/chocolate-fix
